// Project52/frontend/src/pages/Register.jsx
import React from 'react'
import { Form, Input, Button, Card, message, Layout } from 'antd'
import { UserOutlined, LockOutlined, MailOutlined } from '@ant-design/icons'
import { Link, useNavigate } from 'react-router-dom'
import { authAPI } from '../services/api'
import { setAuth } from '../utils/auth'

const { Content } = Layout

export default function Register() {
  const navigate = useNavigate()
  const [loading, setLoading] = React.useState(false)

  const onFinish = async (values) => {
    setLoading(true)
    try {
      const res = await authAPI.register(values)
      setAuth(res.data.access_token, res.data.user)
      message.success('注册成功')
      navigate('/')
    } catch (error) {
      message.error(error.response?.data?.error || '注册失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Layout>
      <Content style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh' }}>
        <Card title="注册" style={{ width: 400, boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}>
          <Form
            name="register"
            onFinish={onFinish}
            autoComplete="off"
            size="large"
          >
            <Form.Item
              name="username"
              rules={[{ required: true, message: '请输入用户名' }]}
            >
              <Input prefix={<UserOutlined />} placeholder="用户名" />
            </Form.Item>

            <Form.Item
              name="email"
              rules={[
                { required: true, message: '请输入邮箱' },
                { type: 'email', message: '请输入有效的邮箱地址' }
              ]}
            >
              <Input prefix={<MailOutlined />} placeholder="邮箱" />
            </Form.Item>

            <Form.Item
              name="password"
              rules={[{ required: true, message: '请输入密码' }, { min: 6, message: '密码至少6位' }]}
            >
              <Input.Password prefix={<LockOutlined />} placeholder="密码" />
            </Form.Item>

            <Form.Item>
              <Button type="primary" htmlType="submit" loading={loading} style={{ width: '100%' }}>
                注册
              </Button>
            </Form.Item>

            <div style={{ textAlign: 'center' }}>
              已有账号？ <Link to="/login">立即登录</Link>
            </div>
          </Form>
        </Card>
      </Content>
    </Layout>
  )
}

// Project55/frontend/src/views/Register.vue
<template>
  <div class="page-container">
    <van-nav-bar title="注册" />
    <div style="padding: 20px;">
      <van-form @submit="onSubmit">
        <van-field
          v-model="form.username"
          label="用户名"
          placeholder="请输入用户名"
          :rules="[{ required: true, message: '请填写用户名' }]"
        />
        <van-field
          v-model="form.password"
          type="password"
          label="密码"
          placeholder="请输入密码"
          :rules="[{ required: true, message: '请填写密码' }]"
        />
        <div style="margin: 16px 0;">
          <van-button round block type="primary" native-type="submit">
            注册
          </van-button>
        </div>
        <div style="text-align: center; color: #1989fa;" @click="goLogin">
          已有账号？立即登录
        </div>
      </van-form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { showToast } from 'vant'
import { userApi } from '../api'

const router = useRouter()
const form = ref({
  username: '',
  password: ''
})

const onSubmit = async () => {
  try {
    const res = await userApi.register(form.value)
    if (res.data.success) {
      localStorage.setItem('user', JSON.stringify(res.data.data))
      showToast('注册成功')
      router.push('/')
    } else {
      showToast(res.data.message)
    }
  } catch (e) {
    showToast('注册失败')
  }
}

const goLogin = () => {
  router.push('/login')
}
</script>
